### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by taufik-nurrohman**

### CODE REVIEW

**Comment by taufik-nurrohman** [comment]
@fransallen Any updates on this? I want to add small improvement on the URL pasting regex to detect GitHub pages assets started with `https://username.github.io`. It should be done in less than one minute.

**Comment by fransallen** [comment]
Regex to detect GitHub Pages would be great! And sorry to be late checking this and making it delayed 1 month rather than 1 minute :P

Oh, adding the 'Copy URL' button to the form might be good, what do you think?

**Comment by taufik-nurrohman** [comment]
> Oh, adding the 'Copy URL' button to the form might be good, what do you think?

As long as it is visible only when there is a value in the input element.

**Comment by fransallen** [comment]
Yep, need to move the focus outline to the generated URL too. Now we can also add options to minify, add `?env=dev`, and use master branch only to the homepage form, do you think we should make it like in the Images page?

**Comment by taufik-nurrohman** [comment]
Minify toggle option is okay but development environment option is no use for average users. Advance users don&rsquo;t even care with the toggle. They will likely to type it into the URL by hand.

**Pull request merged**
